#!/bin/bash

SCRIPT_FOLDER="$HOME/workspace/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [[ -f $SCRIPT_FILE  ]]; then
    vim $SCRIPT_FILE
else
    echo '#!/bin/bash' > $SCRIPT_FILE
    chmod +x $SCRIPT_FILE
fi

